### PR TITLE
Fixed problem that caused suspended modern Win10 apps to be managed

### PR DESCRIPTION
**Pull request by nir9**
Problem:
Windows 10 modern apps invisible windows are randomly appearing every hour or so and taking real estate from dwm-win32 tiles.
Cause:
Windows 10 loads the apps in suspended state to optimize their load time when they are actually needed
Solution:
Make dwm-win32 identify these "cloaked" windows and not manage them

### CODE REVIEW

**Comment by prabirshrestha** [comment]
This seems to completely ignore windows 10 modern apps such as Calculator. would it be possible to not ignore those?

Can you send the debugger commit in different PR so I can merge it.

**Comment by nir9** [comment]
Ok, I see what you are talking about, it looks like the problem is dwm-win32 getting the "new window created" notification while the modern app is still "cloaked" (there is probably some kind of race here).
So I'll try to work on a different solution.

**Comment by prabirshrestha** [comment]
one option is to use this to check which windows are active.

https://www.nirsoft.net/utils/winlister.html

**Comment by nir9** [comment]
WinLister does not solve the problem since it also shows the suspended modern apps as visible windows, and also it is closed source

**Comment by nir9** [comment]
@prabirshrestha Fixed the problem, now it catches modern apps correctly once they are uncloaked

**Comment by prabirshrestha** [comment]
Merged. Thanks for the fix. It has been irritating me too.

Also thanks for fixing list issues. I really need to spend a bit more time to add github actions on some of these.

**Pull request merged**
