### PR TITLE
feat: add move stack

### PR DESCRIPTION
**Pull request by PascalSenn**
migrates https://dwm.suckless.org/patches/movestack/
https://dwm.suckless.org/patches/movestack/dwm-movestack-6.1.diff

### CODE REVIEW

**Comment by nir9** [comment]
Tested, very cool :)
I think you should also include in the PR the needed change in config.def.h, so it will work out of the box:
```
    { MODKEY|MOD_SHIFT,             'J',       movestack,           {.i = +1 } },
    { MODKEY|MOD_SHIFT,             'K',       movestack,           {.i = -1 } },
```

**Comment by prabirshrestha** [comment]
+1 would be good to have config by default.

**Comment by PascalSenn** [comment]
@prabirshrestha  @nir9  Defaults are added

I gave multi monitor a shot but this highly exceeds my C skills :D 
I think this would be the next big feature :D

**Comment by prabirshrestha** [comment]
@PascalSenn you can start by porting some of the code from https://github.com/prabirshrestha/dwm-win32-6. I personally only use one monitor and dwm-win32-6 is quite buggy so stopped using it and went back to this one.

I have been actually thinking of adding lua support for dwm-win32 instead. I started a bit of work with duktape js but didn't like it much as it was old javascript. https://github.com/prabirshrestha/dwmjs. Some how tools I use these days seems to be using lua more such as [wezterm](https://github.com/wez/wezterm). Also I have been sending patches to vim to improve lua support. In linux for the past few months I have been using [awesomewm](https://awesomewm.org/) which is quite powerfull but didn't like much the lua api and the gpl license doesn't help here. I also want to make the bar more customizable hence first need to port lemonbar to win32 which I mentioned it at https://github.com/prabirshrestha/dwm-win32/issues/5.
I have also been very impressed with lua editor here https://github.com/rxi/lite. 

So my ideal goal is to actually have the simplicity of dwm and lemobar with the power of lua that is similar to awesomewm and lite. I have also been thinking of might be using rust instead of c since learning rust haven't been fan of manual memory management in c. Let me know if any of you have preference here or want to stick with just c.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
