### PR TITLE
Added mod_win support and battery status indicator

### PR DESCRIPTION
**Pull request by bert1337**
Added mod_win hot keys (you can replace most system hotkeys) using a WindowsHookEx
Added a battery percentage and charging status indicator on the top bar

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Thanks for the PR.

Is it possible not to change the existing code/styles. We should do this in separate PR and ideally include editorrc.

I can't seem to compile this PR.

```
[100%] Linking C executable dwm-win32.exe
lld-link: error: duplicate symbol: luaopen_bit
>>> defined at D:\tmp\github\dwm-win32\extern\luabitop\bit.c:164
>>>            CMakeFiles/dwm-win32.dir/src/dwm-win32.c.obj
>>> defined at luajit.lib(ljamalg.c.obj)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/dwm-win32.dir/build.make:204: dwm-win32.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/dwm-win32.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

This is what I use.

```
cmake -S . -B build -G "Unix Makefiles" -D USE_LUAJIT=ON   || exit /b
-- CMAKE_BUILD_TYPE not specified, default is 'Debug'
-- The C compiler identification is Clang 10.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/prshrest/scoop/shims/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is Clang 10.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/prshrest/scoop/shims/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/prshrest/scoop/shims/clang.exe
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test NO_STACK_PROTECTOR_FLAG
-- Performing Test NO_STACK_PROTECTOR_FLAG - Success
-- Check target system architecture: x86_64
-- Check target fpu: FPU IS Hard
-- Check target fpu abi: FPU ABI IS Hard
-- Configuring done
-- Generating done
```

**Comment by prabirshrestha** [comment]
@bert1337 let me know if you have plans to address the comments.

**Comment by bert1337** [comment]
> @bert1337 let me know if you have plans to address the comments.

Yes, as soon as I have some free time from work I'll take a look, I'm sorry about not replying earlier

**Comment by prabirshrestha** [comment]
No worries. Take your time.

**Comment by bert1337** [comment]
Ok, can you try now? I've removed the battery indicator and now i think it should compile

**Comment by prabirshrestha** [comment]
I still get the error

```
9 warnings generated.
[100%] Linking C executable dwm-win32.exe
lld-link: error: duplicate symbol: luaopen_bit
>>> defined at D:\tmp\github\dwm-win32\extern\luabitop\bit.c:164
>>>            CMakeFiles/dwm-win32.dir/src/dwm-win32.c.obj
>>> defined at luajit.lib(ljamalg.c.obj)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/dwm-win32.dir/build.make:204: dwm-win32.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/dwm-win32.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

also please make sure the diff is small so I can review. currently it is changing coding style and impacting lot of different lines.

**Comment by prabirshrestha** [comment]
I have added basic CI, so PRs should now run CI if you get the latest changes.

**Pull request closed without merging**
